openapi: 3.1.0
info:
  version: 1.0.0
  title: Travel
  termsOfService: 'https://example.com/terms/'
  contact:
    email: contact@example.com
    url: 'https://example.org/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://raw.githubusercontent.com/FinnNielsen/TravelingApi/main/images/sheepr.gif'
  description:
    $ref: ./info-description.md

tags:
  - name: Directions

servers:
  - url: 'https://{tenant}/api/v1'
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: 'https://example.com/api/v1'

paths:
  /api/v1/travel/directions/:
    post:
      tags:
        - Directions
      operationId: directions
      security:
        - api_key: []
        - basic_auth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/directions_request'
        description: Payload
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Unauthorized

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic

  schemas:

    directions_request:
      type: object
      required:
        - hotel_id
        - from_location
      properties:
        hotel_id:
          type: string
        from_location:
          $ref: ../../components/schemas/v1/location.yaml
